### ISSUE TITLE
Make command line help (especially --flowchart_format) show the default values of arguments where possible

### ISSUE THREAD

**Issue by bjpop** [bunbun/ruffus#51]
Certain command line arguments have default values, such as --flowchart_format.

It would be helpful if the help message showed their default value.

Also the help message for --flowchart_format. says "etc", which is not particularly helpful.

Maybe it would be better if the alternatives were explicitly stated?

**Comment by bunbun** [comment]
I can only see a default value (but following) for --flowchar_format

``--flowchart_format`` for argparse (``cmdline:get_argparse()``) defaults to ``None``, and uses the file extensions from the flow chart file (``--flowchart FILE``) to specify the format. This behaviour is now extended to optparse (``cmdline::get_optparse()``). 

The list of allowable flowchart file formats has been extended.

This is actually not the full list of formats (see http://www.graphviz.org/doc/info/output.html) but all the ones I arbitrarily decided were "sensible". You can still specify the other ones by using them as the file name extension. For example,  ``your_script.py --flowchart wierd.pov``
