### ISSUE TITLE
bug: drmaa_wrapper should use logger.warning instead of logger.warn

### ISSUE THREAD

**Issue by bjpop** [bunbun/ruffus#61]
This ticket relates to the email on the ruffus mailing list with title "possible bug with LoggerProxy?"

The bug causes this exception:

AttributeError: 'LoggerProxy' object has no attribute 'warn'

**Comment by bunbun** [comment]
Many thanks. The fix has been checked in to git hub and will be in the next released version.

**Comment by bunbun** [comment]
Added test code 
test_drmaa_wrapper_run_job_locally.py 
```python
    Test_ruffus.test_read_stdout_stderr_from_files(self)
```
